### PR TITLE
Introduce the documentation team

### PR DESCRIPTION
**Pull request by steveklabnik**
cc https://github.com/rust-lang/rfcs/pull/1683

### CODE REVIEW

**Comment by alexcrichton** [comment]
🚆

**Comment by quodlibetor** [comment]
This doesn't add a link to the docs team from https://www.rust-lang.org/en-US/community.html , which seems to be the main entry point to the teams page.

**Comment by steveklabnik** [comment]
@quodlibetor oh nice catch! Will send a follow-up

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust-www/pull/475

**Pull request merged**
