### PR TITLE
Begin Russian translation

### PR DESCRIPTION
**Pull request by mkpankov**
This is first spike of Russian translation.

I added a layout for non-translated pages, which is a stub saying "This page is not translated. Please help us translate <GitHub .md file edit link> or read English version <link>".

The hope is to facilitate translation by making non-translated pages visible. I also got rid of the verbatim copies of English pages in the text of untranslated pages so that there's no duplicated stuff that needs to be updated in sync with original.

### CODE REVIEW

**Comment by steveklabnik** [comment]
>  Should I just leave off non-translated md's?

This is a good question. I'm not sure what the right answer is.

**Comment by mkpankov** [comment]
@steveklabnik I checked what happens when `ru-RU/documentation.md` isn't present - it causes 404. So I left the untranslated pages and translated the `index.html`.

For future work, maybe it makes sense to default to `en-US` in case there's no file present in the locale? So that it would redirect.

**Comment by steveklabnik** [comment]
Yeah, I think that makes sense.

**Comment by mkpankov** [comment]
Updated the PR. I'm gonna put all the details into edited description and make it no longer WIP. Think it's ready.

**Comment by steveklabnik** [comment]
Great! Thanks so much.

**Pull request merged**
