### PR TITLE
Add SmartThings to friends page

### PR DESCRIPTION
**Pull request by nastevens**
This adds SmartThings to the "Friends of Rust" page. I will send contact information to the rust-logos email address.

### CODE REVIEW

**Comment by nastevens** [comment]
It appears that rust-logos@rust-lang.org is dead - is there an alternate email I can send contact info to?

**Comment by steveklabnik** [comment]
Great, thank you!

> It appears that rust-logos@rust-lang.org is dead - is there an alternate email I can send contact info to?

Uh oh, seems bad. @brson any ideas?

**Comment by nastevens** [comment]
@steveklabnik I can just send to your linked profile email for now, if that works.

**Comment by brson** [comment]
@nastevens The correct address is user-logos@rust-lang.org. Sorry for the inconvenience.

**Comment by nastevens** [comment]
> The correct address is user-logos@rust-lang.org. Sorry for the inconvenience.

No problem - just opened #675 so others aren't tripped up

**Pull request merged**
