### PR TITLE
Translate new install.html to pt-BR

### PR DESCRIPTION
**Pull request by leodasvacas**
Translation to pt-BR of the new `install.html`. I'm feeling lazy about translating `other-installers.md` so if anyone wants to pick that up feel free. Also snuck some minor adjustments. Pinging @lazpeng for review.

### CODE REVIEW

**Comment by lazpeng** [comment]
Nice.
Should have a comma after "English" in "Nosso site em outros idiomas", located in _layouts/pt-BR/basic.html, if you could fix that and add it to the PR, I'd be very grateful. Also, "executar" may be better than "rodar", what do you think?

**Comment by leodasvacas** [comment]
Made suggested changes. In some places "rodar" seems better in others "executar" seems better, I changed it in some places, what do you think now?

**Comment by lazpeng** [comment]
Yeah, that's better, thanks.

**Comment by aturon** [comment]
r? @steveklabnik 

In general, how would you like to handle ongoing reviews of translation PRs?

**Comment by steveklabnik** [comment]
> In general, how would you like to handle ongoing reviews of translation PRs?

Usually, I try to check up on `rust-www` at least once a week to batch it up a bit. It's been a complicated last couple of weeks though. Often, I'll try to CC the people who made the original translation onto changes if they're more than something tiny, but at the moment, the process is effectively 100% trust based.

**Comment by steveklabnik** [comment]
(in this case, @lazpeng is the person I'd want to ask here, so let's merge!)

**Pull request merged**
