### PR TITLE
Fixed [issues #649] and [pull requests #680]

### PR DESCRIPTION
**Pull request by 3442853561**
Fixed issues https://github.com/rust-lang/rust-www/issues/649
Fixed pull requests https://github.com/rust-lang/rust-www/pull/680
Add the date of the migration of beta to stable

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @brson, you may want to take a look at this change

**Comment by 3442853561** [comment]
What is the opinion of you guys? Put "the date of the migration of beta to stable" on which page is better? Index or install? @alexcrichton  @brson

**Comment by brson** [comment]
Hi @3442853561. Thank you for the pr and sorry for taking so long.

While I am ok adding this information to the website, there are things about how this information is displayed that I think can be improved.

Here's a screenshot on my machine: http://imgur.com/a/sok31

The layout here is unbalanced, with much information in a small space, and uneven whitespace. Furthermore, the 'next version' seems like relatively unimportant information, since experienced Rust users will just know the next version, and new Rust users don't need to know.

The 'next version' can also be incorrect in the cases of point releases. "Next scheduled release" might be a more accurate description.

I think this information is not vital enough to appear on the front page. A more fitting place would be the negative space on the install page, beneath version information displayed there.

**Comment by steveklabnik** [comment]
It seems we don't have consensus to merge, and so I'm going to give this a close. Thanks @3442853561 !

**Pull request closed without merging**
