### PR TITLE
 [WIP]Vietnamese translation

### PR DESCRIPTION
**Pull request by hngiang**

### CODE REVIEW

**Comment by hngiang** [comment]
r @brson

**Comment by brson** [comment]
Wow this is amazing! Thank you. Can you rebase?

**Comment by hngiang** [comment]
@brson i have done rebase code, but i missing some page not translated, i'm continue translate page missed, when i'm done you can merge this PR. Thanks @brson

**Comment by brson** [comment]
Thanks again @hngiang! I see there's another conflict here now. I'm happy to merge when they are fixed.

**Comment by hngiang** [comment]
@brson i fixing that.

**Comment by hngiang** [comment]
Many conflicts here, i will open new PR 😸

**Pull request closed without merging**
