### PR TITLE
Change example.rs to a simpler and more welcoming one

### PR DESCRIPTION
**Pull request by tebanep**
This pull request changes the Rust's website example to a more welcoming and simpler one according to issue #754 and as suggested by @3442853561.

This will make Rust seem as an easier language and encourage more people to use it!

### CODE REVIEW

**Comment by brson** [comment]
Thanks @tebanep. This is something I've hoped someone would fix for a long time.

I like the idea of using a multicultural hello world, but am concerned that this example doesn't show much of Rust's character.

I could possibly persuaded that even with that drawback this example is better than the current one.

@steveklabnik do you have opinions?

Here is another thread on the subject to look to for ideas: https://github.com/rust-lang/rust-www/issues/180

**Comment by steveklabnik** [comment]
My opinion is the exact same as yours: I love everything about this _except_ that it doesn't really show off anything about Rust.

> I could possibly persuaded that even with that drawback this example is better than the current one.

Yes, I think we should try to improve this, but if we really can't, let's merge anyway.

@tebanep any idea for something that might be even slightly more complicated? A boring but slightly better example might be putting these strings in a vector and then looping to print? Hm.

**Comment by tebanep** [comment]
Thank you guys for considering this suggestion! Following @steveklabnik recommendation the example now uses an array and a for loop. What I basically did was to write the example as I would in Python and let the compiler point me to the errors and how to fix them. It worked flawlessly! I'm liking Rust very much!

**Comment by 3442853561** [comment]
This is a good idea! BTW, I guess "Bonjour" means "hello" in French.

**Comment by 3442853561** [comment]
What about this example?
```
fn main() { 
    let greetings = ["Hello",
                     "Hola",
                     "こんにちは",
                     "您好"]; 
                     
    for (num,greeting) in greetings.iter().enumerate() { 
        println!("{}", greeting);
        match num {
            0 =>  println!("This code is editable and runnable!"),
            1 =>  println!(""),
            2 =>  println!("このコードは編集して実行出来ます！"),
            3 =>  println!("这个代码是可以编辑并且能够运行的！"),
            _ =>  {},
        }
    }
} 
```

**Comment by brson** [comment]
I'm happy with this as-as, though I like @3442853561's too. I'm going to just merge this and see how it looks live to make project, but I'm happy to keep considering improvements.

**Comment by brson** [comment]
Thanks again @tebanep !

**Pull request merged**
