### PR TITLE
Make note of checkbox on VS install

### PR DESCRIPTION
**Pull request by steveklabnik**
Someone come into #rust-beginners today, and they hadn't done this.

/cc @retep998

### CODE REVIEW

**Comment by steveklabnik** [comment]
http://i.imgur.com/aW5Ai3d.png is a screenshot, maybe we should use it?

**Comment by steveklabnik** [comment]
http://i.imgur.com/6kSmaUe.png

**Comment by alexcrichton** [comment]
I tend to be a little wary of snippets like this, it's 100% guaranteed to go out of date as VS changes their installation procedures and various pieces here and there, and this is quite a prominent location to put this sort of info. This seems like it may be better as an error message in the compiler or something like that.

**Comment by retep998** [comment]
It's a good idea to point out wherever we tell people to install VS that they should make sure they also install the C++ components. Waiting until they've installed VS and installed Rust and then restarted their computer and finally tries to build something only to get an error spit at them that they installed VS wrong isn't very nice.

**Comment by steveklabnik** [comment]
I share the concern about bitrot, but there is a tension here, as the download is huuuuuge

**Comment by brson** [comment]
This is ultimately the kind of thing we want rustup/cargo to detect and make suggestions about. Every additional word we have to add to explain wtf to do to get Rust running also makes me super-duper-sad.

I do think though that if this is where we tell people to get VS, then this is where we have to make it clear exactly what do do.

In a future world where rustup.exe does everything, then rustup.exe can explain it in a platform-dependent way.

As to the picture, I simply will die if we plaster that in the middle of this page. Maybe an inline hyperlink to a lightbox, but still - grrrrr.

**Comment by steveklabnik** [comment]
I wasn't suggesting embedding, just a link or lightbox or something, yeah

**Comment by brson** [comment]
@steveklabnik how about merging this as is and figuring out the pic in another?

**Comment by steveklabnik** [comment]
Sure thing :)

**Comment by brson** [comment]
cc @Diggsey I mentioned above how rustup.exe/multirust can save us from lots of exposition about windows by detecting whether VS exists properly.

**Pull request merged**
