### PR TITLE
New doc, contribution, and FAQ pages

### PR DESCRIPTION
**Pull request by brson**
This PR combines the [documentation](https://github.com/rust-lang/rust-www/pull/241), [contribution](https://github.com/rust-lang/rust-www/pull/229), and [faq](https://github.com/rust-lang/rust-www/pull/202#issuecomment-168873278) PRs along with some extra commits that integrate the FAQ style with the existing website.

It's not perfect, but it's good enough that I'm happy to deploy it as-is and make additional changes as followups.

The only remaining big concerns I have about the FAQ are: HKT section, while better, in the first section makes it sound like Rust has HKT by saying that type constructors that exist are KHTs; there's still no Q&A for 'What does "Rust" mean'.

One last thing I intend to do is make all the FAQs anchors so they can be linked directly, but if necessary that can be a follow up.

[Here's what it looks like](http://brson.github.io/rust-www/).

r? @aturon cc @nikomatsakis

### CODE REVIEW

**Comment by AndrewBrinker** [comment]
I'm so excited to this all coming together! Thanks @brson for a lot of excellent work! And thanks to everyone else who contributed too!

**Comment by bluss** [comment]
:tada:

**Comment by brson** [comment]
With the Rust snippets in the FAQ we'll need to turn on syntax highlighting. I played briefly with enabling both pygments and rouge in jekyll but couldn't get it to work. Can do it in a followup.

**Comment by brson** [comment]
I also think the 'why doesn't rust have exceptions' answer is still to thin.

**Comment by brson** [comment]
Added anchors for every faq.

**Comment by aturon** [comment]
@brson I'm confused about the last commit, adding anchors -- shouldn't this happen automatically upon rendering?

**Comment by aturon** [comment]
@brson @AndrewBrinker I've finally had a chance to comb through the FAQ. I got through about 3/5ths of it this morning, resulting in this counter-PR: https://github.com/brson/rust-www/pull/2

As I said there, I hope to finish going through the rest today and post an additional PR for the later sections.

**Comment by brson** [comment]
@aturon jekyll does not add headers to anchor by default, and I couldn't find an obvious way to make it do so. Happy to take pointers though. Manually creating the anchors also lets the headers be edited later (e.g. I did not make all the anchors correspond to the sometimes verbose headers).

**Comment by aturon** [comment]
@brson OK, that's fine by me.

**Comment by brson** [comment]
Hm, it is possible to set 'with_toc_data' to generate ids on the headers, though that doesn't turn them into links, which is needed to make them discoverable. I also see that my anchor patch is generating incorrect markup. I'll take another pass at it.

**Comment by brson** [comment]
I'll resolve the conflicts in @aturon and @nikomatsakis's pulls myself then fix the anchors somehow.

**Comment by brson** [comment]
@aturon I did augment your 'fearless refactoring' sentence.

I do want to make the anchors here explicit. Since this page is going to be maintained for a long time, it will give more options when changing header text. I think I'll just replace the markdown headers with h3 tags.

**Comment by brson** [comment]
Well, I switched all the h3 headers to HTML instead of markdown. This makes it super ugly since all the code has to be properly html-escaped but it accomplishes my personal goal of having control of the anchor names.

**Comment by brson** [comment]
I've made a few more changes:

I put the project faqs up front since they seem like the logical overview questions. That section had a misplaced 'IDEs' question, so I turned 'Debugging' into 'Debugging and Tooling' and dumped the IDE and rustfmt questions there.

I would have just added a Tooling section, but the 3 column index wants the category count to be a multiple of three.

**Comment by aturon** [comment]
@brson 

OK, I had time to make it through the Project FAQ: https://github.com/brson/rust-www/pull/4

I don't think I'll have time to review the "Other Languages" section, but I think @nikomatsakis has gone through that, so at this point I'm happy to :+1:

This has been an incredible effort. Thanks especially to @AndrewBrinker for the work on the FAQ!

**Comment by tshepang** [comment]
:dancer:

**Pull request merged**
