### PR TITLE
Add ThreatX and Cambridge Consultants to friends

### PR DESCRIPTION
**Pull request by brson**
Closes https://github.com/rust-lang/rust-www/issues/635
Closes https://github.com/rust-lang/rust-www/issues/642

- http://www.cambridgeconsultants.com/
- https://threat-x.com/

Thanks @stusmall and @jonathanpallant!

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
:confetti_ball:

**Comment by stusmall** [comment]
I'm getting a 404 for https://www.rust-lang.org/user-logos/threatx.svg

**Comment by steveklabnik** [comment]
Whoops, totally missed that. @brson has fixed it in https://github.com/rust-lang/rust-www/pull/645

**Comment by stusmall** [comment]
Thanks!

**Pull request merged**
