### PR TITLE
adding a pre tag to use monospace font

### LINKED ISSUE #490: Errors displayed after running front-page code look bad
They are not in an equal width font and have no colors.

### PR DESCRIPTION
**Pull request by rjgoldsborough**
fixes #490 

adds a simple pre tag and uses it

### CODE REVIEW

**Comment by rjgoldsborough** [comment]
old:
screen shot 2016-09-02 at 1 26 54 pm

new:
screen shot 2016-09-02 at 1 41 04 pm

**Comment by rjgoldsborough** [comment]
I'm trying to get the built in jekyll syntax highlighter working but seem to be having trouble.

**Comment by brson** [comment]
Looks good to me. Thanks @rjgoldsborough. Needs a rebase to fix merge conflicts though.

**Comment by brson** [comment]
Since https://github.com/rust-lang/rust-www/pull/506 fixes some additional problems with the parsing of error locations in addition to the formatting, I've merged it, and am closing this. Thank you again for the patch.

**Pull request closed without merging**
