### PR TITLE
Chinese page changes：翻译了一些新内容并且修正了一些有争议的翻译

### PR DESCRIPTION
**Pull request by 3442853561**
Chinese page changes：Translated some new content and revised some controversial translation.
16.10.5

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is failing due to the BOM issue, could you fix it please, @3442853561

**Comment by 3442853561** [comment]
@steveklabnik I couldn't fix it,I don't understand Ruby.

**Comment by lifthrasiir** [comment]
@3442853561 BOM is an invisible character at the very beginning of the file, and used to determine the endianness of UTF-16 text (thus not recommended in UTF-8). You have to strip the BOM in your change---as you can see below, the first line is seemingly not modified but marked as changed.



If you don't know how to strip BOM in your editor, please let us know what editor you are using.

**Comment by 3442853561** [comment]
Thank you @steveklabnik  and @lifthrasiir 
I fix it!(smile)
非常感谢，我修好了（笑）

**Comment by steveklabnik** [comment]
> I fix it!(smile)

Thanks! :D

**Pull request merged**
