### PR TITLE
Translate contribute.md to ru/RU

### PR DESCRIPTION
**Pull request by TyanNN**
Somebody should also translate contribute-* sometime

### CODE REVIEW

**Comment by mkpankov** [comment]
@TyanNN hi! Thanks for your work on Russian translation.

We over at @rurust are also doing some translation.

In the interest of coordination, could you please join us at in [Gitter chat](https://gitter.im/ruRust/offtopic) or IRC (#rust-ru) and discuss further work?

**Comment by TyanNN** [comment]
@mkpankov sure

**Comment by mkpankov** [comment]
@steveklabnik we've reviewed this PR in @rurust and think it can be merged. Some remaining rough edges in translation fill be fixed by follow-up PRs.

**Comment by brson** [comment]
Thanks @TyanNN  and @mkpankov !

**Pull request merged**
