### PR TITLE
Fixed language codes for fr-FR and es-ES

### PR DESCRIPTION
**Pull request by AndrewBrinker**
Instead of #659.

This PR renames the `fr/` language code to `fr-FR/` and does the same for `es/` to `es-ES/`. It also adds missing layouts for `es-ES/`, although they are currently just copies of the default layouts.

### CODE REVIEW

**Comment by 3442853561** [comment]
This is a good idea to regulate the localization of the page. However the French page just changed from "fr-FR" to "fr". I think the name "fr" is a better practice.

**Comment by steveklabnik** [comment]
Liquid Exception: Included file '_includes/fr-FR/example.rs' not found in fr-FR/index.html

>  However the French page just changed from "fr-FR" to "fr".

Yes, this was my mistake.

**Comment by AndrewBrinker** [comment]
@steveklabnik, should be fixed now.

**Comment by steveklabnik** [comment]
Thanks!

**Comment by AndrewBrinker** [comment]
No problem! :smile:

**Pull request merged**
