### PR TITLE
Add timestamp of last site build to error page

### PR DESCRIPTION
**Pull request by edunham**
Useful for debugging purposes, and establishing whether Cloudfront
invalidation was done correctly. {{site.time}} inserts the current time when
the page is being built.

r? @alexcrichton

### CODE REVIEW

**Comment by steveklabnik** [comment]
What about putting it into an HTML comment, so it's not directly displayed on-page?

**Comment by edunham** [comment]
ok, it's a comment now. Also threw in a contributing guide for reasonably-obvious docs on the existance of the timestamp. 

Please don't merge until Travis is green:  I need to argue with it a bit about how not to run impossible commands on PRs, and I'll be rebuilding this commit as my test case.

**Comment by brson** [comment]
Merge conflicts.

**Comment by edunham** [comment]
Okay, I think in theory that we are good to merge now.

**Pull request merged**
