### PR TITLE
Fixed Italian è vs é; better .gitignore for macOS

### PR DESCRIPTION
**Pull request by ituxbag**
The 3rd person of Italian "essere" (= to be) verb is è, not é. It's a serious error.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by ituxbag** [comment]
@alexcrichton I'm reviewing the Italian translation and I saw that ALL accents are wrong. Now, I have a partial patch made with sed covering only è / é characters (I can apply same procedure on other characters); but may be I could accidentally changed some characters in the links to other languages (for example Brazillian). Reviewing word by word would be an hell .... :-(

How can I proceed? I make a pull request and the translators of other languages will review the links?
Thank you.

**Comment by alexcrichton** [comment]
cc @gabibbo97, thoughts? (you did the [original translation](https://github.com/rust-lang/rust-www/pull/678))

**Comment by gabibbo97** [comment]
@alexcrichton  Yup, he is right, using the US International keyboard made me swap the correct accent over each "e" with an accent.
I think we can safely replace every wrong accent with a well structured find & replace operation in any editor

**Comment by alexcrichton** [comment]
Ok, thanks @gabibbo97! Want to make a PR @ituxbag?

**Comment by gabibbo97** [comment]
@ituxbag Sorry for my mistake, you are 100% correct

> Reviewing word by word would be an hell
Yup but if you really need any help I'd gladly mentor you

**Comment by ituxbag** [comment]
@alexcrichton @gabibbo97 I made the PR https://github.com/rust-lang/rust-www/issues/723.

**Pull request merged**
