### PR TITLE
Update to VS 2017 tools

### PR DESCRIPTION
**Pull request by steveklabnik**
This includes at least changing the URLs of the non-english pages, they could use a look over by the respective maintainers of each translation.

### CODE REVIEW

**Comment by steveklabnik** [comment]
People who have touched these files:

* @hngnaig
* @laurence6
* @malbarbo
* @lazpeng
* @leodasvacas
* @starsep
* @3442853561
* @lifthrasiir
* @KeenS
* @Wakamatz
* @ykomatsu
* @gabibbo97
* @ituxbag
* @robitex
* @AndrewBrinker
* @TheoChevalier
* @belltoy
* @justinchuby
* @brson 

I'm going to merge this anyway since the URLs should be correct, but please check if you want to modify any of the translation pages! I'm sorry that I didn't get on top of this sooner so we could have coordinated beforehand, I didn't realize until yesterday that this was shipping today!

**Comment by gabibbo97** [comment]
The modifications are correct for _it-IT_

**Comment by lazpeng** [comment]
pt-BR is also fine

**Comment by hngnaig** [comment]
correct for vi-VN

**Pull request merged**
