### PR TITLE
Improve browser detection and install instructions

### PR DESCRIPTION
**Pull request by brson**
Fixes https://github.com/rust-lang/rust-www/issues/692

Corresponding rustup PR: https://github.com/rust-lang-nursery/rustup.rs/pull/936

cc @wezm

r? @steveklabnik

### CODE REVIEW

**Comment by brson** [comment]
The "unknown" install box is now stuffed full of text, with the default install instructions. It's not aesthetic, but this is a rare case.

**Comment by brson** [comment]
This also fixes an error in the markup where a div was improperly nested in a p.

**Comment by steveklabnik** [comment]
Looks good to me. @wezm what do you think?

**Comment by wezm** [comment]
I don't have access to my FreeBSD machine right now to test but the code changes look good to me.

**Pull request merged**
