### PR TITLE
ko-KR: Caught up with recent page additions.

### PR DESCRIPTION
**Pull request by lifthrasiir**
Most significantly, this PR fully re-translates `install.html` and `other-installers.md`.

Nit: I'm very unsure about the addition of Weibo links to the localized pages, as I believe Weibo is virtually alien to Korean speakers. I have temporarily commented the paragraph out for that reason but I have no other problem to make it visible.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@lifthrasiir sorry this has been sitting awhile! Want to rebase and I'll merge?

**Comment by lifthrasiir** [comment]
@alexcrichton Sure, I should have taken a look at what has been updated since the last commit anyway.

**Comment by lifthrasiir** [comment]
@alexcrichton I've rebased and updated the translation to the current (duplicated default installation instructions, updated user groups). r?

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
