### PR TITLE
Rename "Community" nav header to "Resources"

### PR DESCRIPTION
**Pull request by brson**
This way "Community" isn't repeated.

r? @steveklabnik

### CODE REVIEW

**Comment by brson** [comment]
cc @aturon

**Comment by brson** [comment]
This is temporary until the docs page is redesigned, but it will be a long temporary.

**Comment by aturon** [comment]
SGTM. The repeated "Community" is a bit weird at the moment. "Resources" is generic but at least avoids the repetition.

One question: why is `News` called out currently, given that it's also linked in Community? With this refactor, I'd at least suggest moving the `Community` link to the top, since it contains the largest set of leads.

**Comment by brson** [comment]
@aturon The question about 'News' was also brought up on IRC. It's fairly arbitrary.

I've removed it and instead added the security policy.

**Comment by brson** [comment]
cc @steveklabnik Adding security policy to front page.

**Comment by steveklabnik** [comment]
Really glad to see this get more attention :+1:

**Pull request merged**
