### PR TITLE
增加简体中文页面

### PR DESCRIPTION
**Pull request by 3442853561**
add Simplified Chinese  page

### CODE REVIEW

**Comment by 3442853561** [comment]
dear @steveklabnik HELP!

**Comment by Hoverbear** [comment]
Hi Ryuki! 

I noticed your message on IRC. Someone will look at this soon, but there are several conferences happening this week related to Rust. You may need to be patient. :)

The tests are green, someone has been assigned to review this, and things look in order. **Thank you** for making this contribution. Someone will look at this, but you need to give us some time.

**Comment by steveklabnik** [comment]
Yes, it's just going to take a little bit, due to the conference. Sorry! :( I very much want this patch, but I also don't want to just click "merge" without reviewing

**Comment by steveklabnik** [comment]
Thank you so much! Sorry again about the delay in reviewing.

**Pull request merged**
