### PR TITLE
Add i18n links docs

### PR DESCRIPTION
**Pull request by rjgoldsborough**
first pass at fixing #487 

adding links to footer and a translations contrib page

### CODE REVIEW

**Comment by steveklabnik** [comment]
As usual with these kinds of changes, mind posting a screenshot? I know @brson and @aturon care a lot about the look of the website, so they'll want to weigh in here too.

**Comment by rjgoldsborough** [comment]
These are the footer, the added item to the end of the contribute list, and the stub page I made. I'm not exactly sure what is wanted there so I left it for now. I could try to come up with something though I suppose.

screen shot 2016-08-30 at 12 43 29 pm
screen shot 2016-08-30 at 12 43 41 pm
screen shot 2016-08-30 at 12 43 52 pm

**Comment by brson** [comment]
@rjgoldsborough Do you mind pushing your branch to gh-pages so we can see it live? I think that would make it easier to get a feel for how it looks across the entire site.

**Comment by rjgoldsborough** [comment]
Hmm pushed it here https://rjgoldsborough.github.io/rust-www/en-US/ but seem to have build issues or something else is going on. This page is unstyled.

When I go to https://rjgoldsborough.github.io/rust-www it redirects to https://rjgoldsborough.github.io/en-US for some reason.

**Comment by rjgoldsborough** [comment]
The build error is that rust-lang CNAME is already used.

**Comment by rjgoldsborough** [comment]
Ah, looks like the site is using absolute urls for styles, images, etc

**Comment by rjgoldsborough** [comment]
The css url is set to `<link rel="stylesheet" href="/css/style.css">` but mine is being served from
`/rust-www/css/style.css` not `/css/style.css`

It wasn't too hard to get it running locally. I could also try to host this elsewhere?

**Comment by steveklabnik** [comment]
Finally got the opportunity to clone this down locally. Looks good to me; we'll need to get it translated on each page as well, but you don't have to worry about that.

@brson did you get the chance to play with this?

**Comment by brson** [comment]
Yeah it looks good to me. Thanks @rjgoldsborough!

**Comment by rjgoldsborough** [comment]
Thank y'all! Lemme know if you want someone to update this again after the docs are written or more is translated or anything else.

**Pull request merged**
