### PR TITLE
[WIP] Romanian translation

### PR DESCRIPTION
**Pull request by boghison**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you! First of all, so sorry for missing the review here. Assigning myself.

It says that there are merge conflicts that need to be resolved; could you take care of them please? Thanks!

**Comment by boghison** [comment]
OK. BTW, which files have the most priority for translation? I don't think I'll have the time to translate every one of them.

**Comment by steveklabnik** [comment]
I'm not sure we've ever picked; we're just now starting to get translations, so we haven't done this a ton before. I would imagine the homepage is the most important, followed by the downloads page, followed by everything else, but I'm not sure.

**Comment by brson** [comment]
Since this hasn't moved in a long time I'm going to close it. Thank your for the translation, and feel free to reopen again if anybody wants to continue with it.

**Pull request closed without merging**
