### PR TITLE
[WIP] - Turkish translation

### PR DESCRIPTION
**Pull request by bonesoul**
This is a work-in-progress and please don't merge in yet :) I'm opening this PR early to let any other potential contributers for tr-TR translation.

I'll let you know, once we are all done.

### CODE REVIEW

**Comment by steveklabnik** [comment]
> I'll let you know, once we are all done.

Please do! Thanks :)

**Comment by steveklabnik** [comment]
@bonesoul any updates here?

**Comment by bonesoul** [comment]
basically the main pages were dont, let me re-check tomorrow and fix conflicts so we can get it in.

**Comment by steveklabnik** [comment]
@bonesoul I'm going to give this one a close for inactivity; if you want to update it, please let me know and I'm more than happy to re-open!

**Pull request closed without merging**
