### PR TITLE
添加了简体中文的连接连接

### PR DESCRIPTION
**Pull request by 3442853561**
adding Chinese(Simplified) link

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @steveklabnik 

Although looks like some other work may need to be done on the infrastructure? Right now the site doesn't seem to render well :(

https://www.rust-lang.org/zh-CN/

**Comment by GuillaumeGomez** [comment]
There is a syntax error (an unexpected '%').

**Comment by steveklabnik** [comment]
> Although looks like some other work may need to be done on the infrastructure? Right now the site doesn't seem to render well :(

Yikes!

**Comment by steveklabnik** [comment]
It seems that jekyll is just straight-up copying `zh-CN/index.html` into the `_site` directory rather than doing the templating. I have no idea why.

**Comment by steveklabnik** [comment]
Okay, it has to be something specific, becuase if I copy the english one over into the zh-CN folder, it does render it. wtf.

**Comment by steveklabnik** [comment]
Okay, I fixed it: https://github.com/rust-lang/rust-www/pull/541

Now that it's rendering properly, I think this is a good idea. Thanks!

**Pull request merged**
