### PR TITLE
Upgrade jekyll

### PR DESCRIPTION
**Pull request by steveklabnik**
Two commits here: the first is a jekyll upgrade, and the second introduces the lockfile to version control.

r? @brson

### CODE REVIEW

**Comment by brson** [comment]
Let's wait to merge this until not right after the release.

**Comment by steveklabnik** [comment]
Seems fine. I will be sending a similar PR for the blog as well.

**Comment by brson** [comment]
We can merge this when it's rebased.

**Comment by steveklabnik** [comment]
@brson done!

**Comment by steveklabnik** [comment]
had to do some stuff to get travis to be happy, but should be good to go

**Pull request merged**
