### PR TITLE
Add a documentation page. Restructure navigation

### PR DESCRIPTION
**Pull request by brson**
This adds a documentation page to the website, to replace the in-tree landing pages, and restructures the top level navigation to have only 'Documentation', 'Community', 'Downloads', and 'Contribute' links.

The security, legal and FAQ pages are all linked from the docs page.

To deal with nightly and beta docs I just included a section called 'nightly and beta documentation' that goes only to the in-tree landing page for those, the thinking being that they are less important, and for more knowledgeable users. So I did not try to duplicate all the relevant information for all three channels ala the downloads page.

For non-english resources I deferred to [rust-learning](https://github.com/ctjhoa/rust-learning) temporarily, though I'd prefer to use the [forge](https://internals.rust-lang.org/t/dungeon-rust-lang-org-secondary-developer-docs/2896) for that. I [opened a PR](https://github.com/ctjhoa/rust-learning/pull/26) against rust-learning to include all the book translations.

For other useful resources I again deferred to rust-learning. To keep things non-overwhelming I like having secondary resources on another page, though perhaps rust-learning will not be that page in the future.

You can see this deployed, along with the contributions page [here](http://brson.github.io/rust-www/index.html).

Needs to wait on the [contributions](https://github.com/rust-lang/rust-www/pull/229) page to merge, and if it merges before the [FAQ](https://github.com/rust-lang/rust-www/pull/202) then it needs to be edited to make the FAQ link work.

Fixes https://github.com/rust-lang/rust-www/issues/179. cc https://github.com/rust-lang/rust-www/issues/175

cc @efindlay @aturon @steveklabnik

### CODE REVIEW

**Comment by brson** [comment]
I used [Go](https://golang.org/doc/) and [Scala](http://scala-lang.org/documentation/) as references.

**Comment by aturon** [comment]
The docs page looks pretty good to me. I just have a couple of overall worries:

- The various policy docs now feel a bit buried. Granted, these things are often given as small links at the bottom of a page anyway, so it's not clear that this is much worse -- my main concern is I wouldn't think of "Documentation" as the place to find them. At the very least, I think we should have a distinct "Policy" subsection of documentation, and ultimately we'll be able to add docs on e.g. the governance setup and RFC process there.

- The layout of the front page seems... off... somehow. In particular, the whitespace around the top links seems excessively, and none of the elements in the main body align with each other. I'm struggling to be more constructive -- maybe I should just fiddle with it on a branch and see if I can demonstrate what I have in mind.

**Comment by brson** [comment]
I've pushed a commit to split out a 'project policies' section. Adding a section on 'policies' generally suggests we need more links there. One possibly is the link explaining Rust governance and processes that I have mentioned to you previously.

I've been thinking about adding a footer across the site, particularly to explain how to submit changes to the website itself, possibly to explain the copyright of the website itself. We could add other legal links there, but frankly I think we should not, because they are not so important that that they should be available from every page of the website.

I'm going to be doing some work on integrating the FAQ styling with the rest of the site. Part of this may be touching how the header is separated from the content. I'll see if anything there suggests ways to make this header look more balanced.

**Comment by brson** [comment]
I've pushed a change to my deployment that adjusts the style of the site to accomodate the styling of the faq. The changes are described [here](https://github.com/rust-lang/rust-www/pull/202#issuecomment-168873278). Part of this adds a border element to most pages near the navbar, and it also reduces the whitespace around the navbar on the index page.

**Comment by aturon** [comment]
@brson Looking very good! I think the separate policy section works well, and agree that it's a natural place to talk about governance, etc. (Though I don't think we have to do that for this initial round of website updates).

My only (very small) nit is that the horizontal rule separating the header from the rest seems thinner than the rule separating the different sections, which felt a bit jarring.

But overall the rules and large section headers feel pretty good as a way to present a lot of information in a manageable and simple way.

**Comment by brson** [comment]
On reddit /r/killercup suggested that the [syntax index](https://github.com/rust-lang/rust/pull/30814) should be advertised more widely. I already added it to rust-learning, and I'm tempted to add it to the references section.

**Comment by aturon** [comment]
@brson Sounds like a good idea to me.

**Comment by brson** [comment]
@aturon My latest version uses a consistent-width horizontal rule everywhere.

This PR is subsumed by [that].

**Pull request closed without merging**
