### PR TITLE
Update the list of personal characteristics to synchronize with the Contributor's Covenant v1.3

### PR DESCRIPTION
**Pull request by nikomatsakis**
This PR updates the list of personal characteristics to synchronize with the [Contributor's Covenant v1.3](http://contributor-covenant.org/version/1/3/0/). This is not intended as a change to the actual meaning of the CoC, since all of these characteristics were intended to be implied by the original wording. However, making the list more explicit is clearer for readers overall, and the CC seems to have a reasonable list.

r? @rust-lang/core 
cc @rust-lang/moderation

UPDATE: Tweaked wording of this PR proposal somewhat.

### CODE REVIEW

**Comment by Manishearth** [comment]
:+1: from me

**Comment by steveklabnik** [comment]
:+1:

**Comment by alexcrichton** [comment]
Sounds good to me, thanks @nikomatsakis!

**Comment by aturon** [comment]
cc @Charlotteis 

Strong :+1: for me. I like being more explicit, and especially the addition of "level of experience". I also think sync'ing with the current best practices here is a good way to go.

**Comment by brson** [comment]
Lgtm. Thanks @nikomatsakis

**Comment by niconii** [comment]
:+1:

**Comment by mbrubeck** [comment]
+1

**Comment by pnkfelix** [comment]
looks fine with me. (at first I thought "gender, gender ..." was a typo, but I can understand differentiating between "gender" and "gender identity/expression")

**Comment by huonw** [comment]
:+1:

**Comment by BurntSushi** [comment]
:+1:

**Comment by nikomatsakis** [comment]
OK, at this point everyone on the core team (and many on the mod team) have either commented here or spoken with me privately and approved this PR. Therefore, I am going to merge it. Thanks all!

**Comment by niconii** [comment]
:tada: :confetti_ball: :tada:

**Comment by nikomatsakis** [comment]
Just FYI, I also announced this change on the [users] and [internals] boards.

[users]: https://users.rust-lang.org/t/recent-clarification-to-the-code-of-conduct/4390
[internals]: https://internals.rust-lang.org/t/recent-clarification-to-the-code-of-conduct/3105

**Pull request merged**
