### PR TITLE
Reference C++ templates in section on monomorphization

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by AndrewBrinker** [comment]
The policy has been not to compare Rust to other languages outside of the "Other Languages" section. People reading the FAQ come from lots of different backgrounds, and we can't assume they know C++. My preference is to continue with that policy.

**Comment by djc** [comment]
This is actually part of the "Other languages" section, though?

**Comment by AndrewBrinker** [comment]
Oh geez, you're right. This is why I shouldn't try to give feedback on PRs right after waking up.

It's probably fine to reference C++ here, although I worry that people will make incorrect assumptions about how Rust traits and C++ templates compare. It's probably worthwhile to add an answer explaining the differences between them.

**Pull request merged**
