### PR TITLE
Complete italian translation

### PR DESCRIPTION
**Pull request by gabibbo97**
Hello my fellow Rustaceans.
I have made the effort to translate the entire Rust website to italian.
The translation of the Rust website is **complete**

This is my first contribution ever to an open source project so _please be kind_

### CODE REVIEW

**Comment by steveklabnik** [comment]
> This is my first contribution ever to an open source project so please be kind

Looks great to me so far! However, due to some other changes, you'll need to rebase this before we can merge. I can absolutely help you with that if you need any.

**Comment by gabibbo97** [comment]
Thanks @steveklabnik I should now have managed to get the branch to merge cleanly.

**Comment by steveklabnik** [comment]
Great! Do you want me to merge this as-is, or do you have more work to do? You mentioned that you wanted to do at least one part in another PR...

**Comment by gabibbo97** [comment]
Thanks for your help @steveklabnik, as I stated beforehand I would like to terminate the translation of the FAQ page before finally being merged, I will update this pull request with the final details probably around 20 CEST of the 12 of Jan because tomorrow I am attending two exams so I will probably be busy.

In the meanwhile I will ensure that the automatic merge can be performed without conflicts with the base branch and directly state its status of completeness in another comment.
After declaring the PR as ready you can be free to merge it as soon as you want.

After that I might try to still get involved into getting the Italian translation synced with the upstream en-US one.

Let's keep in touch for later, and thanks for your help!

**Comment by steveklabnik** [comment]
>  I am attending two exams so I will probably be busy.

That's super okay, thank you so much for the work so far, and good luck on your exams! Just let me know when this is ready to ship 😄

**Comment by gabibbo97** [comment]
Ok, sorry for the delay, now the translation is complete, including the FAQ page

**Comment by steveklabnik** [comment]
Merged! Thanks 😄

**Pull request merged**
