### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by starsep**
# Status: DONE. Please review and merge.
Hi, I've started translating page to Polish.
I'll highly appreciate any feedback.

### CODE REVIEW

**Comment by brson** [comment]
Seems good to me. I'm happy to merge after rebasing. Thanks so much @starsep !

**Comment by starsep** [comment]
It took a while but I finally translated all the things I've wanted to.
I didn't know how to translate properly some things so I've left English terms.

**Comment by starsep** [comment]
@brson Any updates? I've translated all the things I've wanted to.
If there any bugs/typos etc. I happy to fix them.

**Comment by alexcrichton** [comment]
Sorry for the delay @starsep! Want to rebase, ping me, and I'll merge?

**Comment by starsep** [comment]
@brson @alexcrichton 
I've rebased.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
